version: '2'

services:
  dcc-dashboard-service:
    environment:
      APACHE_PATH: "${apache_path}"
      DATABASE_URL: "${database_url}"
      FLASK_APP: "/app/mapi.py"
      DCC_DASHBOARD_HOST: "${dcc_dashboard_host}"
      L_POSTGRES_USER: "${login_user}"
      L_POSTGRES_PASSWORD: "${login_password}"
      L_POSTGRES_DB: "${login_db}"
      SECRET_KEY: "${secret_key}"
      ES_DOMAIN: "${es_domain}"
      ES_PORT: "${es_port}"
      ES_PROTOCOL: "${es_protocol}"
    #image: quay.io/ucsc_cgl/dashboard-service:1.0.0
    volumes:
      - ~/dcc-dashboard-service/logs:/app/log
    build: dcc-dashboard-service
    ports:
      - "80"
      - "443"
    networks:
      - server
      - login
    ports:
      - "9200"
    links:
      - login-db
    restart: always
  dcc-dashboard:
    #image: quay.io/ucsc_cgl/dashboard:1.0.0
    build: dcc-dashboard
    ports:
      - "80"
      - "443"
    volumes:
      - ~/dcc-dashboard/logs:/app/log
#      - dashboard1:/app
    environment:
      GOOGLE_CLIENT_ID: "${google_client_id}"
      GOOGLE_CLIENT_SECRET: "${google_client_secret}"
      DCC_DASHBOARD_HOST: "${dcc_dashboard_host}"
      DCC_DASHBOARD_PROTOCOL: "${dcc_dashboard_protocol}"
      DCC_DASHBOARD_SERVICE: "${dcc_dashboard_service}"
      L_POSTGRES_USER: "${login_user}"
      L_POSTGRES_PASSWORD: "${login_password}"
      L_POSTGRES_DB: "${login_db}"
      SECRET_KEY: "${secret_key}"
      LOG_IN_TOKEN: "${login_token}"
      SERVER_NAME: "${dcc_dashboard_host}"
      DCC_CORE_CLIENT_VERSION: "${core_client_version}"
      ES_DOMAIN: "${es_domain}"
      ES_PORT: "${es_port}"
      ES_PROTOCOL: "${es_protocol}"
      BD_POSTGRES_USER: "${login_user}"
      BD_POSTGRES_PASSWORD: "${login_password}"
      BD_POSTGRES_DB: "burndown"
    networks:
      - server
      - login
    links:
      - login-db
    restart: always
  nginx:
    build: nginx-dev
    links:
      - dcc-dashboard
      - dcc-dashboard-service
    environment:
      - VIRTUAL_HOST=${dcc_dashboard_host}
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=redirect
      - LETSENCRYPT_HOST=${dcc_dashboard_host}
      - LETSENCRYPT_EMAIL="default@email.com"
    mem_limit: 2g
    cpu_shares: 256
    ports:
      - "80"
      - "443"
    networks:
      - core_public
      - server
    restart: always
  boardwalk:
    #image: quay.io/ucsc_cgl/boardwalk:1.0.0
    build: boardwalk
    environment:
      - BOARDWALK_HOST=${dcc_dashboard_host}
      - BW_DATA_URL=${dcc_dashboard_protocol}://${dcc_dashboard_host}
      - BEARER_TOKEN=${login_token}
    networks:
      - server
    ports:
      - "80"
      - "443"
      - "3000"
    volumes:
      - boardwalk1:/usr/src/app
    restart: always
  login-db:
    image: postgres:9.6-alpine
    container_name: "login-db"
    environment:
      POSTGRES_PASSWORD: "${login_password}"
      POSTGRES_USER: "${login_user}"
      POSTGRES_DB: "${login_db}"
    volumes:
      - login_postgres:/var/lib/postgresql/data
    networks:
      - login
    restart: always

volumes:
  login_postgres:
    driver: local
  dashboard1:
    driver: local
  boardwalk1:
    driver: local
networks:
  core_public:
    external: true
  server:
    driver: bridge
  login:
    driver: bridge
